export OTEL_TRACES_EXPORTER="otlp"
export OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4318"
export OTEL_NODE_RESOURCE_DETECTORS="env,host,os"
export OTEL_SERVICE_NAME="fastify-otel-poc"
export NODE_OPTIONS="--require @opentelemetry/auto-instrumentations-node/register"
